### ISSUE TITLE
保存出来的PNG文件尺寸太大速度太慢(画布较大时的问题)

### ISSUE THREAD

**Issue by Amaoimn** [F-know/F_Record#1]
画布比较大的时候，每次导出的png尺寸也太大，录制效率很低。实际最终导出的视频大多数是1080P即可，似乎没有必要按照原大尺寸输出PNG

**Comment by nextatmo** [comment]
解决方案似乎是录制的时候就等比缩小就好了

**Comment by F-know** [comment]
很好的建议，下个版本我会尝试去优化
