### ISSUE TITLE
UP可以把网盘里分享的结果放在Github Release这里

### ISSUE THREAD

**Issue by shandianchengzi** [F-know/F_Record#2]
夸克网盘需要登录还挺麻烦的~而且还会限速嗐。
我习惯性地直接clone了整个仓库，但是加载的时候显示未签署，估计是因为最新的修改没有被签署。如果有Release版本会好一些。

---

最后：我已经从夸克网盘下载并用上插件啦！很好用！还支持画布的变化！感谢作者！我准备去推广给列表的画手太太们！

**Comment by F-know** [comment]
多谢提醒，我已经上传了Release，直接使用仓库源代码确实会有问题，原因似乎是github调整了我代码的一些格式，导致PS验证签名失败

**Comment by shandianchengzi** [comment]
好滴，那我close啦
