### ISSUE TITLE
"unable to load the extension" error in Photoshop

### ISSUE THREAD

**Issue by Affabulateur** [F-know/F_Record#5]
I tried to install it but I have the following error : "unable to load extension" 
How can I fix this please ?

**Comment by F-know** [comment]
如果你下载的仓库源代码使用，就可能会出现这个问题，原因似乎是github对我上传的代码做了一些格式上的调整，这导致了PS对插件签名验证失败。所以我刚刚上传了Release，你可以根据你电脑的系统下载win.zip或mac.zip来使用。

**Comment by Affabulateur** [comment]
Awesome thank you !!
