### ISSUE TITLE
Mac version to Gihub?

### ISSUE THREAD

**Issue by wolendranh** [F-know/F_Record#6]
Thank you your package! It seems really interesting, but it from "pan.quark".
Do you plan on releasing Mac version to github anytime soon?

Thank you in advance

**Comment by F-know** [comment]
前几天我在github上上传了release，里面包含了Mac版本，可以直接下载

**Comment by wolendranh** [comment]
@F-know thank you for quick response! I will look into that

**Comment by wolendranh** [comment]
I was able to get release version working. Thank you once again! 
I would suggest adding information into README about running extension on ARM mac hardware (M processors). To load plugins on ARM version of MAC it requires to run Photoshop in "Rosetta" mode (check "open with Rosetta" in "get info" file window of Photoshop app icon)
